on:
  push:
    branches: [main]
    paths:
      - 'ocpnv.go'
      - 'ocpnv_test.go'
    tags-ignore:
      - 'v*'
  pull_request:
    branches: [main]

name: Go CI

env:
  GO111MODULES: auto

jobs:
  lint:
    name: Lint Files
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
  test:
    name: Run Tests
    runs-on: 'ubuntu-latest'
    needs: lint
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - run: go test -v -cover
